name: build

on:
  push:

env:
  IMAGE_NAME: bgauduch/cod2server

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Docker image
      run: docker build . --file Dockerfile --tag $IMAGE_NAME:latest
    - name: Save Docker image
      run: docker image save -o image.tar $IMAGE_NAME:latest
