name: build

on:
  push:

env:
  IMAGE_NAME: bgauduch/cod2server

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Branch name
        run: echo running on branch ${GITHUB_REF##*/}

      - name: Build Docker image
        run: docker build . --file Dockerfile  --build-arg COD2_VERSION="1_3" --build-arg COD2_LNXDED_TYPE="_nodelay_va_loc" --tag $IMAGE_NAME:${GITHUB_REF##*/}
