name: image build

on:
  push:
  pull_request:

env:
  IMAGE_NAME: bgauduch/cod2server

jobs:

  build:

    # needs: lint

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $IMAGE_NAME:latest
