name: push latest

on:
  push:

env:
  IMAGE_NAME: bgauduch/cod2server

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build . --file Dockerfile --tag $IMAGE_NAME:latest

    - name: Login to Docker Hub registry
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

    - name: Push image to Docker Hub registry
      run: docker push $IMAGE_NAME:latest
