name: push latest

on:
  push:
    # branches:
    #   - master

env:
  IMAGE_NAME: bgauduch/cod2server

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Branch name
      run: echo running on branch ${GITHUB_REF##*/}
    - name: Build Docker image
      run: docker build . --file Dockerfile --tag $IMAGE_NAME:${GITHUB_REF##*/}
    - name: Login to Docker Hub registry
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    - name: Push image to Docker Hub registry
      run: docker push $IMAGE_NAME:${GITHUB_REF##*/}
